
version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: gieuser 
      POSTGRES_PASSWORD: giepassword 
      POSTGRES_DB: giedb 
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: gie_lms_app 
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://gieuser:giepassword@localhost:5432/giedb
    depends_on:
      - postgres

volumes:
  postgres_data:

