version: '3.8'

services:
  postgress:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: giepostgres
      POSTGRES_PASSWORD: gieschool
      POSTGRES_DB: giedb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: gie_lms
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://giepostgres:gieschool@localhost:5432/giedb
    depends_on:
      - postgres

volumes:
  postgres_data:
